# Generated by Django 4.1.5 on 2023-01-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='Address',
            field=models.CharField(max_length=200),
        ),
    ]
