# Generated by Django 4.1.5 on 2023-01-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_friend_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Debit', models.IntegerField(default=False)),
                ('Credit', models.IntegerField(default=False)),
                ('Balance', models.IntegerField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
