# Generated by Django 4.1.5 on 2023-01-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_category_table_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='Debit',
            field=models.IntegerField(null=True),
        ),
    ]
