# Generated by Django 4.1.5 on 2023-01-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_table_credit_alter_table_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Balance',
            field=models.IntegerField(),
        ),
    ]
