# Generated by Django 4.1.5 on 2023-01-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_table_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
