# Generated by Django 4.1.5 on 2023-01-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
