# Generated by Django 4.1.5 on 2023-01-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='Credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='Debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
