# Generated by Django 4.1.5 on 2023-01-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_table_balance_alter_table_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Debit_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
