# Generated by Django 4.1.5 on 2023-01-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_table_debit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Getback',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
