# Generated by Django 4.1.5 on 2023-01-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_table_getback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Description',
        ),
    ]
